### ISSUE TITLE
Numba version requirement in version 0.3.3 too low

### ISSUE THREAD

**Issue by AlexSchuckert** [weinbe58/QuSpin#271]
The dependency requirement for numba going from version 0.3.2 to version 0.3.3. needs to be updated I think. Using numba version 0.42.1 still worked in 0.3.2., however in version 0.3.3. I get the below error, which is I think coming from make_c_struct in numba (see 1.8.4.2. in this doc: https://numba.pydata.org/numba-doc/dev/user/cfunc.html). This error is fixed when updating numba to the latest version, so I guess one could update the version requirement for numba in the installation of quspin 0.3.3. to fix this.

Traceback (most recent call last):
  File "XXXX", line 18, in <module>
    from quspin.operators import hamiltonian # Hamiltonians and operators
  File "XXX/lib/python2.7/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "XXX/lib/python2.7/site-packages/quspin/operators/__init__.py", line 52, in <module>
    from .quantum_operator_core import *
  File "XXX/lib/python2.7/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "XXX/lib/python2.7/site-packages/quspin/basis/__init__.py", line 123, in <module>
    from quspin.basis.user import *
  File "XXX/lib/python2.7/site-packages/quspin/basis/user.py", line 1, in <module>
    from .basis_general.base_user import (user_basis,map_sig_32,op_sig_32,next_state_sig_32,count_particles_sig_32,
  File "XXX/lib/python2.7/site-packages/quspin/basis/basis_general/base_user.py", line 17, in <module>
    op_results_32 = types.Record.make_c_struct([
AttributeError: type object 'Record' has no attribute 'make_c_struct'

**Comment by weinbe58** [comment]
Thank you for pointing this out!
