### ISSUE TITLE
Operator expectation value in spin full fermion basis

### ISSUE THREAD

**Issue by shaktiimaan** [weinbe58/QuSpin#340]
Hello, I am interested in to evaluate expectation value of an operator which change the particle number of  a state by acting on it.
So let's say I am having a creation operator at site 1 (\c_1^\dagger).  I am operating it on a state which is obtained by daigonalizing  some hamiltonian in basis of fixed particle number n where lattice sites are N. So this operator will change the particle number of the state from n to n+1. 
1.) This is one point where I do not how to use Quspin  to operate such operators on a state. which changes the particle number.

Now I wants to take the dot product of this new obtained state with particle number (n+1) with some different state  obtained by daigonalizing  some hamiltonian in basis of particle number fixed n+1.

2.) This is second point where I don't understand how should I go ahead. 

Since I can not use matrix_ele(Vl, Vr, time=0, diagonal=False, check=True) because Vl belongs to n particle basis state and vr belongs to n+1 particle basis state. But  definitely my operator connects these states. 

If you have any confusion in my question please let me know.

Thanking you.

**Comment by weinbe58** [comment]
So there are two ways of dealing with this:

**Method one:** work in the basis with N (+) N+1 particle basis: 

To do this all you have to do is specify the particle sectors as a list in for `Nf=...` input into your basis. In this basis your hamiltonian is block diagonal within the particle sectors but your creation operator is not. If you do this you can treat the creation operator just like a regular operator with QuSpin. Use can use the total particle operator to separate out eigenstates that have different particle numbers.

**Method two:** use the `Op_shift_sector` method of the basis class.

This method is far more efficient because the memory required is far less and you can work with two independent sets of Hamiltonians. I think its easier if you go through [example 19](http://weinbe58.github.io/QuSpin/examples/example19.html#example19-label) then if I try to explain it here. 

Let me know if you need any more explanations.

**Comment by shaktiimaan** [comment]
Thank you for quick response,
Firstly I wants to understand method one, 
**Method one**: So If I am working with N (+) N+1 particle basis. and having a state in this basis. This time also if I operate creation operator on this state, it changes its particle number to (N+1) and (N+2).  And I am not sure QuSpin can do such job, where operator changes the state particle number. 
Another I did not understood, how to use "**total particle operator to separate out eigenstates that have different particle numbers**".

**Method two** : I tried using this earlier but I am getting a run time error saying :

`in Op_shift_sector
for opstr,indx,J in op_list:
ValueError: not enough values to unpack (expected 3, got 2)`

A short part of the code is here 
 `psi1 = basis.Op_shift_sector(basis_1, operator ,psi[:,0])`
where **basis** is n+1 particle basis and **basis_1 and state psi[:,0]** belongs  to n particle basis. So I am expecting psi1 to be n+1 particle basis state. 

If you need full code to see the error, let me know. 

Thanks

**Comment by weinbe58** [comment]
So for *method one* You are only interested in matrix elements between sectors N and N+1 so even if you have transitions to other sectors the matrix elements are not included in your hamiltonian. Think of picking the particle sectors as doing a hard projection onto that quantum number.  In this basis with two particle sectors you get eigenstates with both N and N+1 particles from diagonalizing `H` but they will be sorted by energy and not by particle number. you can use the total particle number, which is simply $N_{tot}=\sum_i n_i$, to distinguish the eigenstates with different particle numbers: The code would look something like this:

```python

# generate H and Ntot above
E,V = H.eigh()

# enforce_pure=True makes it so that the function does not assume V is density matrix
Ntot_eb = Ntot.expt_value(V,enforce_pure=True) 

m_N = Ntot == N # eigenstates with N fermions
m_Npo = Ntot_eb == N+1 # eigenstates with N+1 fermsions

V_N = V[:,m_N]
V_Npo = V[:,m_Npo]

```

For *method two* I can get a better sense if you post the full code. its not clear what the issue is from that error message.

**Comment by shaktiimaan** [comment]
Thanks 
here is my code using  **Op_shift_sector**
`from __future__ import print_function, division
from quspin.basis import spinful_fermion_basis_general
from quspin.operators import hamiltonian
import numpy as np

###### define model parameters ######
L=12    #number of sites
#basis with 9 particles
basis=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(5,4),(4,5),(1,8),(8,1),(3,6),(6,3),(2,7),(7,2),(1,8),(8,1),(0,9),(9,0)])
#basis with 8 particles
basis_1=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(4,4),(5,3),(3,5),(6,2),(2,6),(7,1),(1,7),(8,0),(0,8)])

e=[[1,0,0]]
f=[[-1,0,0]]

static=[["+-|",e],["|+-",f]]

H=hamiltonian(static,[],basis=basis,dtype=np.float64,check_pcon=False)
H1=hamiltonian(static,[],basis=basis_1,dtype=np.float64,check_pcon=False)
E,ww=H.eigsh(k=1,which='SA',maxiter=1E10,return_eigenvectors=True)
E1,ww1=H1.eigsh(k=1,which='SA',maxiter=1E10,return_eigenvectors=True)

p=[[1,1]]
static1=[["+|",p]]

#H11=hamiltonian(static0,[],basis=basis_2d1,dtype=np.float64,check_pcon=False,check_herm=False)#check_symm=False)

#........Here I am operating creation operator at site 1 on state ww1[,0] which belongs to particle  number n=8 in basis_1, and wants to convert it to a state with basis n+1 =9 particles .......# 

psi1 = basis.Op_shift_sector(basis_1,static1,ww1[:,0])
print(psi1.shape,ww[:,0].shape)
a=np.dot(ww[:,0],psi1,out=None)
print(a)`

**Comment by shaktiimaan** [comment]
Is my code explanatory, what I wants to evaluate?
If you need some clarification, let me know.

Thanks

**Comment by weinbe58** [comment]
What you have is almost correct you just need to change:

```python 

# old
p=[[1,1]]
static1=[["+|",p]]

# new
p=[[1]]
static1=[["+|",p,1.0]]

```

However, there is a bug within the spinful_fermion_basis_general code at this point so it will not work.

**Comment by weinbe58** [comment]
if you want you can download and manually install the version of quspin with the fixes. I will post here with further instructions if you would like.

**Comment by shaktiimaan** [comment]
Still getting error saying:
`return spinless_fermion_basis_general.Op_shift_sector(other_basis,new_op_list,v_in,v_out=v_out,dtype=dtype)	
TypeError: Op_shift_sector() missing 1 required positional argument: 'v_in'
`

part of code where error is encountering
`psi1 = basis.Op_shift_sector(basis_1,static1,ww1[:,0])`

thanks

**Comment by shaktiimaan** [comment]
Hello 
Can you tell me the source of this error, which I am getting in this Op_shift_sector in the updated version, or you guys are still working on the update. of this routine.
Thanks

**Comment by shaktiimaan** [comment]
I am sorry to bother again, but is still there any issue in this routine or I am making mistake?

**Comment by weinbe58** [comment]
Its an issue with QuSpin, your code is fine. If you want you can manually install dev_0.3.5 which has the fixes. do you know how to install a python package manually?

**Comment by shaktiimaan** [comment]
I don't know what this package is for? Do I have to download this package separately and need to install or can I directly install it using conda?

**Comment by weinbe58** [comment]
Sorry, I mean to say the bug fixes have not been formally released so you can't update QuSpin via anaconda, however you can download the current github branch dev_0.3.5 which has the fixes. You have to install this version of QuSpin from the source code directly instead of installing it via conda.

**Comment by shaktiimaan** [comment]
Thank you! 
I am installing it manually, but at many stages I am getting an error saying 

`Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]`

**Comment by weinbe58** [comment]
Yes don't worry about that, its not a problem

**Comment by shaktiimaan** [comment]
somehow installation failed and compiler says  
`failed with exit status 1`.
And I am getting same error. 
`Op_shift_sector() missing 1 required positional argument: 'v_in' `

**Comment by weinbe58** [comment]
first, you have to remove the old version from anaconda `conda remove quspin` then rerun the installation. 
read more about the installation [here](http://weinbe58.github.io/QuSpin/Installation.html)

**Comment by shaktiimaan** [comment]
I was getting issues while installing it. So I tried a different way I installed again using conda itself and replaced one line 645
as indicated in issue [here](https://github.com/weinbe58/QuSpin/pull/343/commits/91e9bb26f9053326dd00727aede1b07ba1c4988b).
in file  anaconda3/python3.7/site-packages/quspin/basis/basis_general/fermion.py
Is this the only change in updated version or they're more changes.

But I am getting an error 
`ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

**Comment by shaktiimaan** [comment]
It works in g++ 9.3 compiler. 
but I am getting import errors
 `  File "example0.py", line 12, in <module> ` 
`from quspin.operators import hamiltonian # Hamiltonians and operators`
  `File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/__init__.py", line 3, in <module>`
    `from . import operators`
`File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/operators/__init__.py", line 54, in <module>`
    `from .quantum_operator_core import *`
  `File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/operators/quantum_operator_core.py", line 3, in <module>`
    `from ..basis import spin_basis_1d as _default_basis`
`  File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/basis/__init__.py", line 117, in <module>`
`    from .basis_1d import *`
  `File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/basis/basis_1d/__init__.py", line 1, in <module>`
    `from .spin import spin_basis_1d`
 ` File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/basis/basis_1d/spin.py", line 1, in <module>`
   ` from ._basis_1d_core import hcp_basis,hcp_ops`
  `File "/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/basis/basis_1d/_basis_1d_core/__init__.py", line 1, in <module>`
    `from . import hcp_basis,hcp_ops`
`ImportError: cannot import name 'hcp_basis' from partially initialized module 'quspin.basis.basis_1d._basis_1d_core' (most likely due to a circular import) (/home/aman/QuSpin-dev_0.3.5/examples/scripts/../../quspin/basis/basis_1d/_basis_1d_core/__init__.py)`

**Comment by weinbe58** [comment]
I compiled this version with g++ 7 and it worked I'm checking g++ 9 but in the meantime try g++ 7

**Comment by shaktiimaan** [comment]
What about these Import Errors while running example scripts? Are these also due to g++ version, or I am made some mistake while installing?

**Comment by weinbe58** [comment]
I think the issue isn't anything to do with g++, have you tried moving the scripts into another folder and running them?

**Comment by shaktiimaan** [comment]
It is running now, thank you so much for answering every question in details. 
But still Op_shift_sector routine is giving error:
`File "shift_op_ex.py", line 33, in <module>`
    `psi1 = basis.Op_shift_sector(basis_1,static1,ww1[:,0])`
  `File "/home/aman/anaconda3/lib/python3.8/site-packages/quspin/basis/basis_general/fermion.py", line 647, in Op_shift_sector`
    `return spinless_fermion_basis_general.Op_shift_sector(self,other_basis,new_op_list,v_in,v_out=v_out,dtype=dtype)`
 ` File "/home/aman/anaconda3/lib/python3.8/site-packages/quspin/basis/basis_general/base_general.py", line 416, in Op_shift_sector`
    `self._core.op_shift_sector(v_in,v_out,opstr,indx,J,`
  `File "quspin/basis/basis_general/_basis_general_core/source/general_basis_core.pyx", line 274, in quspin.basis.basis_general._basis_general_core.spinful_fermion_core.general_basis_core_wrap.op_shift_sector`
`
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

here is my short code--
[shift_op_ex.txt](https://github.com/weinbe58/QuSpin/files/5125730/shift_op_ex.txt)

**Comment by shaktiimaan** [comment]
Yeah, it works now. 
Thank you!
